version: '2'
services:
  odoo:
    image: jalvcl/odoo_base:11
    container_name: odoo
    restart: always
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - PORT=5432
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./_config:/etc/odoo
      - ./odoo/extra-addons:/mnt/extra-addons
  db:
    image: postgres:10
    container_name: db
    restart: always
    command: -p 5432
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - 'odoo-db-data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'  
volumes:
  odoo-web-data:
    # driver: local
  odoo-db-data:
    # driver: local