#Depuration
# remove TTY create error COMPOSE_HTTP_TIMEOUT

version: '2'
services:
  odoo74:
    image: jalvcl/odoo_base:11
    container_name: odoo74
    restart: always
    depends_on:
      - db74
    command: --xmlrpc-port 8074
    command: --log-level debug --log-request --log-response
    environment:
      - HOST=db74
      - USER=odoo
      - PASSWORD=odoo
      - PORT=5474
    ports:
      - "8074:8074"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./_config:/etc/odoo
      - ./odoo/extra-addons:/mnt/extra-addons
  db74:
    image: postgres:10
    container_name: db74
    restart: always
    command: -p 5474
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - '5474:5474'
volumes:
  odoo-web-data:
    driver: local
  odoo-db-data:
    driver: local